
#ifndef __AMI_CONFIG
#define __AMI_CONFIG

#define ENABLE_DISK_WARNINGS	0
#define ENABLE_CHIP_WARNINGS	0
#define ENABLE_CIA_WARNINGS		1
#define ENABLE_COPPER_WARNINGS	0
#define ENABLE_DISPLAY_WARNINGS	0


#endif//__AMI_CONFIG

