
DISABLE_DISPLAY=0

ifeq ($(DISABLE_DISPLAY),1)
LD_SDL=
CFLAGS=-DDISABLE_DISPLAY=1
else
LD_SDL=-lSDL -lSDLmain
CFLAGS=-I/usr/include/SDL -DDISABLE_DISPLAY=0
endif

run:	blitter.c blitter.h display.c display.h memory.c memory.h main.c cpu.c cpu.h ciachip.c ciachip.h customchip.c customchip.h copper.h copper.c
	gcc $(CFLAGS) -O0 -g blitter.c display.c main.c memory.c ciachip.c customchip.c cpu.c copper.c $(LD_SDL) -o run
